name             'graphite'
maintainer       'Marcy'
maintainer_email 'marcy9114@gmail.com'
license          'All rights reserved'
description      'Installs/Configures graphite'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'openssl'
depends          'mysql'
depends          'database'
depends          'yum'