#Graphite Web Settings
default[:graphite][:timezone]       = "Asia/Tokyo"
default[:graphite][:mysql_password] = "graphite"
#Carbon Settings
default[:graphite][:storage_dir]               = "/var/lib/carbon/"
default[:graphite][:local_data_dir]            = "/var/lib/carbon/whisper/"
default[:graphite][:enable_log_rotation]       = true
default[:graphite][:max_updates_per_second]    = 500
default[:graphite][:max_creates_per_miniute]   = 50
default[:graphite][:line_receiver_interface]   = "0.0.0.0"
default[:graphite][:line_receiver_port]        = 2003
default[:graphite][:enable_udp_listener]       = false
default[:graphite][:udp_receiver_interface]    = "0.0.0.0"
default[:graphite][:udp_receiver_port]         = 2003
default[:graphite][:pickle_receiver_interface] = "0.0.0.0"
default[:graphite][:pickle_receiver_port]      = 2004
default[:graphite][:log_listener_connections]  = true
default[:graphite][:use_insecure_unpickler]    = false
default[:graphite][:cache_query_interface]     = "0.0.0.0"
default[:graphite][:cache_query_port]          = 7002
default[:graphite][:use_flow_control]          = true
default[:graphite][:log_updates]               = false
default[:graphite][:log_cache_hits]            = false
default[:graphite][:log_cache_queue_sorts]     = true
default[:graphite][:cache_write_strategy]      = "sorted"
default[:graphite][:whisper_fallocate_create]  = true
default[:graphite][:whisper_autoflush]         = false
